// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "simple-model-front",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://simple-model-front.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
